- name: Check for Python3
  raw: test -e /usr/bin/python3
  changed_when: false
  failed_when: false
  register: check_python

- name: Install Python
  raw: apt -y update && apt install -y python-minimal
  when: check_python.rc != 0

- name: Install NodeJS
  become: yes
  become_method: sudo
  become_user: root
  command: apt install -y nodejs

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


