- name: Check for Python3
  raw: test -e /usr/bin/python3
  changed_when: false
  failed_when: false
  register: check_python

- name: Install Python
  raw: sudo apt -y update && apt install -y python-minimal
  when: check_python.rc != 0

- name: Install NodeJS
  raw: sudo apt install -y nodejs

- name: Fix NPM
  raw: sudo ln -s /usr/local/bin/npm /usr/bin/npm

- name: Install PM2
  raw: sudo /usr/bin/npm install pm2 -g

- name: Export Env Variables
  raw: export ENVIRONMENT=production && export DB=XXX

