- name: Copy backend files
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Stopping backend service
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 stop backend
    pm2 delete backend

- name: Installing backend
  shell: |
    cd /home/ubuntu/backend    
    npm install        

- name: Building backend service
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Run backend migrations
  shell: |
    cd /home/ubuntu/backend
    npm run migrations

- name: Running backend service
  shell: |
    cd /home/ubuntu/backend    
    pm2 start npm --no-automation --name "backend" -- run start
