- name: Copy backend files
  copy:
    src: /root/project/backend
    dest: /home/ubuntu/backend

- name: Starting backend service
  shell: |
    cd /home/ubuntu/backend/backend    
    npm install
    npm run build
    pm2 start npm -- start:prod -- name "backend"

