- name: Copy backend files
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Starting backend service
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    npm run start:prod
#    pm2 start npm -- start:prod -- name "backend"
