version: 2.1

jobs:
  build-test-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Install backend"
          command: |
            cd backend
            npm install

workflows:
  default:
    jobs:
      - build-test-backend
